export enum AppView {
  LANDING = 'LANDING',
  AUTH = 'AUTH',
  ONBOARDING = 'ONBOARDING',
  DASHBOARD = 'DASHBOARD',
  SOLDIER_PORTAL = 'SOLDIER_PORTAL',
  DIGITAL_PAPER = 'DIGITAL_PAPER'
}

export interface Soldier {
  id: string;
  name: string;
  surname: string;
  age: number;
  rank: string;
  exitDate: string;
  rejoinDate: string;
  isApproved: boolean;
  approvalSignature?: string; // Generated by Gemini
  approvalTimestamp?: string;
  phoneNumber?: string;
}

export interface MilitaryFieldProfile {
  name: string;
  location: string;
  address: string;
  commanderName: string;
}

export interface UserSession {
  email: string;
  isAuthenticated: boolean;
  profile?: MilitaryFieldProfile;
}
